### ISSUE TITLE
Updating Removes Videos

### ISSUE THREAD

**Issue by hardknoxni69a** [CkauNui/ckau-book#10]
Currently If I Update It Will Erase Everything In The Ckau-Book Folder And Start From Scratch. This Is More Like A Reinstall Not An Update. I Have Taken Full Advantage Of The Theme And Have Uploaded The Extra Videos. Unfortunately Each Update All My Uploads Are Deleted. Is There A Way To Make It Update And Add All The New Theme Files But If There Are Separate Video Files Uploaded By The User To Leave Them Alone? This Will Make It So The User Does Not Have To Reupload Any Additional Video Files During An Update. Keep Up The Great Work Thanks!

**Comment by CkauNui** [comment]
No, before update just rename or move other place.

**Comment by hardknoxni69a** [comment]
Ok was hoping it was as simple change of how the copy works to compare and keep newest files. Like rysnc -u

**Comment by CkauNui** [comment]
Moved all addons outside the theme folder, in order to preserve addon files when updating theme through EmulationStation.

/themes/ckau-book - theme directory
/themes/ckau-book-addons - addons directory, which will not be overwritten by ES update procedure.
