### ISSUE TITLE
Black border issue on various vieuwstyles

### ISSUE THREAD

**Issue by Derik-for-real24** [CkauNui/ckau-book#111]
hello, I have some minor issue with Ckau Book theme which I like to show you

The first issue is related with CKau Book- vieuwstyle **Carousel + Detail**, I applied this vieuwstyle exclusively to my Collections wheel.
Here is the thing, when you start ES for the first time,  images will be shown correct, as seen on the image below, the area that im talking about is marked in green by me.

![Ckau Book-1](https://github.com/CkauNui/ckau-book/assets/108466376/d59cf951-2a72-44c0-9646-2433eadcf71a)

However, for example when I go inside my Race collection and then go back to Collections main screen, then the images gets messed up, like on the picture below.

![Ckau Book-2](https://github.com/CkauNui/ckau-book/assets/108466376/35876a1b-cba8-4741-98d7-424277faeb68)

The second issues is about black borders on the bottom nd top of the screen and also the sides in various Vieuwstyles; Detailed, Detailed dark, GameCarousel, DetailWheel, Grid+Deails nd more). Let me break it down for you, any game related to emulation (gba,megadrive, psx etc) where media content is scraped from Screenscrapper, these games dont have noticeable black borders, there is a very slight black border though, and some games have black border on the sides or top nd bottom of screen depending on the game platform see images below.

![Ckau Book-blackborder on sides](https://github.com/CkauNui/ckau-book/assets/108466376/6871fed7-4ef2-4855-9aa9-9ed959e77665)

![Ckau Book-blackborder on top nd bottom](https://github.com/CkauNui/ckau-book/assets/108466376/c1d96aba-5a59-49e7-b87e-d2eea2adc861)

Finaly, regarding the black borders this time for windows titles, I scraped my media files through youtube nd images through google, the results are pretty brutal because the black borders on Images nd videos is significantly noticeable compared to the above images which were scraped from ES build in Screenscraper. Let me show you what I mean on the image below.

![Ckau Book-blackborders issue](https://github.com/CkauNui/ckau-book/assets/108466376/80ba5669-cc7d-4b45-8160-cd2cc88d2059)

![Ckau Book-blackborder Windows 1](https://github.com/CkauNui/ckau-book/assets/108466376/0f8b252d-80eb-4dc8-ace5-25a832f8f8cb)

![Ckau Book-blackborder Windows 2](https://github.com/CkauNui/ckau-book/assets/108466376/45d04271-cdfe-4d95-b401-08377843ac6c)

I have these issues on 2 systems running on Windows  11, the first is my main pc running on 4k screen aspect ratio 16:9 , second system is Steamdeck running on 1280x800 screen aspect ratio 16:10.

I hope there is a solution to these problems, I mean your theme is absolute perfection, but these little things just makes you always think about it.

Really hope to find a resolution to fix this, its my favorite theme.

**Comment by CkauNui** [comment]
For Black bars - as a temporary solution u can delete "_inc/images/**space.png**"

**Comment by Derik-for-real24** [comment]
Thnx men, it worked to resolve the black bars, but it comes at a price.

After deletion of inc/images/space.png , basically the entire background turns completely dark, so not same color as before I deleted the file. I would preffer to have the dark background color back.

Some viewstyles show game description but extremely hard to read, mostlikely related to the change of background collor into complete black backround color.

**Comment by CkauNui** [comment]
1. problem in ES.
2. deleted "video-screen" and "video-background" and resize video \ screenshot place for old view.
