### ISSUE TITLE
Zx81 background.

### ISSUE THREAD

**Issue by vitauser1** [CkauNui/ckau-book#13]
Similar request for zx81 background.

png of zx81
![](https://ajournalofmusicalthings.com/wp-content/uploads/Sinclair-ZX81.jpg)

Tape player from time
https://www.pngaaa.com/api-download/2117116

Could be same tv as zx spectrum.

hope it helps!

thanks!

Let me know if you need other pics, I don’t mind digging around to find them.

**Comment by vitauser1** [comment]
Description

The ZX81 is a home computer that was produced by Sinclair Research.  It was launched in March 1981 as the successor to Sinclair's ZX80 and designed to be a low-cost introduction to home computing for the general public. It was hugely successful; more than 1.5 million units were sold.
In the United States it was initially sold under licence by Timex. Timex later produced its own versions of the ZX81: the Timex Sinclair 1000 and Timex Sinclair 1500.

**Comment by vitauser1** [comment]
![](https://www.techrepublic.com/a/hub/i/2011/02/21/5b7d1231-c3ab-11e2-bc00-02911874f8c8/DSC_0208-1200x800.jpg)

**Comment by vitauser1** [comment]
I had a go...got it working on mine...sharing in case it's any use to you....

![zx81](https://user-images.githubusercontent.com/51163242/128628692-53ca8e2d-b814-4830-912b-96ecb0988af2.png)


[zx81.xml.txt](https://github.com/CkauNui/ckau-book/files/6950536/zx81.xml.txt)

**Comment by CkauNui** [comment]
Thx! Can u send me PSD file?

**Comment by vitauser1** [comment]
[Untitled_Artwork.zip](https://github.com/CkauNui/ckau-book/files/6986303/Untitled_Artwork.zip)

here you go,  was done by my daughter on ipad so hope it works….

**Comment by vitauser1** [comment]
![4F158EFE-F37C-4299-94CD-E5BF53D287FD](https://user-images.githubusercontent.com/51163242/129444252-fa84a316-53d8-46f0-af91-492f304bce71.jpeg)
![1CC2485A-8A45-4F48-AD96-D57639EBB029](https://user-images.githubusercontent.com/51163242/129444254-fe2cbbc3-259c-4389-ab37-ffa543bd551b.jpeg)

**Comment by vitauser1** [comment]
Procreate file
[Untitled_Artwork.zip](https://github.com/CkauNui/ckau-book/files/6986353/Untitled_Artwork.zip)

**Comment by CkauNui** [comment]
hmm psd no have layers. Ok, can disable light and set bg color to 161616
Need for darkful :)
