### ISSUE TITLE
Change system image

### ISSUE THREAD

**Issue by Podgers95** [CkauNui/ckau-book#131]
Hello, I tried to replace the image of the amstradcpc with the model 6128 (with the floppy disk drive and not the cassette), that's the one I had when I was a kid. unfortunately, if the image appears in the menu, it is cropped during the animation and the video on the screen does not play :(. How to do it? thank you

**Comment by Podgers95** [comment]
![amstradcpc modif](https://github.com/CkauNui/ckau-book/assets/164688773/7278033f-dcfb-4c61-a653-4669f129d4ef)

**Comment by CkauNui** [comment]
need change video pos \ size and anim in "layouts\amstradcpc.xml"

**Comment by Podgers95** [comment]
These parameters can be found in several places in the file. I guess background1 is before translation, background is after? But even if I take the original image, open it modified, add a red circle (so no modification of where the screen is positioned) it doesn't work anymore. The image shifts correctly to the left, but no video, neither before nor after the shift. But it must be there because I can hear the sound!!!

![2024-03-24_15h20_15](https://github.com/CkauNui/ckau-book/assets/164688773/9f9266b1-04ed-4e2a-8491-4b2f7c7753fd)

**Comment by Podgers95** [comment]
i use paint to edit the image

**Comment by Podgers95** [comment]
OK I understand better by playing with the parmeters. I think it has to do with the fact that my "screen" in my image isn't transparent? Or is the video "in the background" and behind it?

Can we have the name of the video that's playing? I'd like to display it above the screen to inform the name of the game that is currently displayed:
		<video name="videobox" extra="true">
			<path>{random}</path>

**Comment by CkauNui** [comment]
As i say "need change video pos \ size and anim in "layouts\amstradcpc.xml""

**Comment by Podgers95** [comment]
Thanks for your help. It wasn't a position problem, the image had no transparency, so it was impossible to display a video. Now I've got the Amstrad 6128 and the video. I just need to know how to get the name of the game displayed on the screen. Can you tell me if it's possible to retrieve it? It's the random element of

<video name="videobox" extra="true">
			<path>{random}</path>
