### ISSUE TITLE
Missing background for light gun collection

### ISSUE THREAD

**Issue by Asculpus** [CkauNui/ckau-book#14]
Hello! I’m currently using the ckau-book theme and for some reason the lightgun collection has a logo but no background. It’s just a black screen with the default lightgun logo. Every other category works. I’ve read around a lot and most answers say just copy and paste in a background but this theme’s XML is mostly in russian. I had the same issue with the RVGM as well. I’m on x64 on a PC and have updated to batocera v32. Any help would be great thanks.

**Comment by CkauNui** [comment]
Hi, auto-lightgun.png and lightgun.png include in theme in colorful presets. What presets u use?

**Comment by Asculpus** [comment]
I've included my configuration and what it currently looks like. Thanks for
getting back to me!
