### ISSUE TITLE
Regional features removed

### ISSUE THREAD

**Issue by KTac** [CkauNui/ckau-book#149]
I see that a few days ago the ability to have region specific artwork was removed. Why is that? It was very nice to be able to have the versions of the consoles I grew up with displayed, and it was working great. This seems like a step backwards for this otherwise excellent theme. I updated the theme in Batocera and lost all my region specific consoles and I can't get them back.

**Comment by CascaCure** [comment]
I also noticed this feature removal upon updating the theme to the latest version. I really liked having US Logos and System-images, etc. displayed when I set the Region to US. Kindly requesting that this setting be re-implemented, please.

This is my favorite EmulationStation theme by far, thanks to all for your wonderful work on a great theme. Hoping the Regional Features can be brought back.

**Comment by CkauNui** [comment]
Don't worry, they haven't been removed, many people want to see different regions at the same time. That is, how nes, so and famicom, snes, sfc, dreamcast, dreamcast-jp and others.
There will be instructions soon, but for now you can simply use these files (https://github.com/g-spawnPL/ckau-book-custom-systems) to display systems from other regions.

**Comment by CkauNui** [comment]
back regional features
