### ISSUE TITLE
Missing Sufami Turbo Screen

### ISSUE THREAD

**Issue by chaps1983** [CkauNui/ckau-book#15]
Notice that the logo appears but receive a black screen when using theme via Batocera. notice image is missing from artwork but have seen a copy online. see attached image
![Sufami_Turbo](https://user-images.githubusercontent.com/100082874/154850079-438fe6f7-e649-42b5-baf2-01165befc593.jpg)
can this be edited/added to the artwork?

**Comment by CkauNui** [comment]
add
