### ISSUE TITLE
Hack systems - nesh, genh, snesh - hack overlay transitions when No Anim is set

### ISSUE THREAD

**Issue by rogs123** [CkauNui/ckau-book#157]
Hi - thank you so much for the theme, incredible piece of work.

Per the title, when  Colorful (No Anim) is selected, the "hack" overlays still transition to the left of the screen. Correct behavior is that the overlay should not move. Tested with nesh, genh, snesh layouts.

Thanks!

**Comment by rogs123** [comment]
I added the following to noanimate.xml to fix:

		<video name="videoglich" extra="true">
			<storyboard>
				<visible>0</visible>
			</storyboard>
		</video>

**Comment by CkauNui** [comment]
Done, thanks ;)
