### ISSUE TITLE
Hide total games counter in platfrom view

### ISSUE THREAD

**Issue by vahacris** [CkauNui/ckau-book#160]
Can You please tell me where I can find option or line in xml file to hide total games counter in platfrom view (marked on attached picture)? 

The theme is great but I like to keep it as clean ass possible. Best regards.
![qqq](https://github.com/user-attachments/assets/af0b46b0-f0dc-4aae-a41b-b687a535e1d5)

**Comment by vahacris** [comment]
solve it myself. you need to change theme.xml

change:
<view name="system">
		<text name="systemInfo" extra="static">
			<backgroundColor>14141400</backgroundColor>
			<color>777777FF</color>
			<fontPath>./_inc/fonts/ubuntu_condensed.ttf</fontPath>
			<pos>0.85 0.945</pos>
			<size>0.09 0.058</size>
			<alignment>right</alignment>
			<fontSize>0.025</fontSize>
			<zIndex>110</zIndex>
		</text>

to:
<view name="system">
		<text name="systemInfo" extra="static">
			<backgroundColor>14141400</backgroundColor>
			<color>777777FF</color>
			<fontPath>./_inc/fonts/ubuntu_condensed.ttf</fontPath>
			<pos>0.85 0.945</pos>
			<size>0.09 0.058</size>
			<alignment>right</alignment>
			<fontSize>0.025</fontSize>
			<zIndex>1</zIndex>
		</text>

**Comment by Lendersmark** [comment]
Hi @vahacris, we added an option to hide the total number of games. No need to manually change theme.xml.
It will be published soon, in the next version of the theme.
