### ISSUE TITLE
3DS videos not split

### ISSUE THREAD

**Issue by GinSoakedBoy** [CkauNui/ckau-book#167]
Would it be possible to have an option to play scraped videos for the 3DS on the top screen only on the main screen? I've found that scraped videos for 3DS games are only single screen so look like this:

![SCR-20241204-moyf](https://github.com/user-attachments/assets/cdce456b-bd70-4386-8a87-62c89f7d6068)

Original DS games seems to have split videos so look fine:

![SCR-20241204-mpdw](https://github.com/user-attachments/assets/2c827ad0-1f2f-4485-a337-7d8bb92c0fbe)

**Comment by CkauNui** [comment]
Hi, you need to use the "correct" videos or the preset ones in the theme or "[COLORFUL Video Pack](https://github.com/CkauNui/ckau-book-addons-Colorful-Video)"

**Comment by GinSoakedBoy** [comment]
Do you have any recommendations for where to scrape the correct style videos? Screenscraper.fr only has single screen style videos for 3DS.

**Comment by CkauNui** [comment]
record them yourself

**Comment by GinSoakedBoy** [comment]
Fair enough. I'll look into that, thanks. For now, I'm gonna use the video from the colorful video pack just for the 3DS.

I do wonder why all the videos on Screenscraper for the DS are of both screens but for the 3DS are just the main screen.
