### ISSUE TITLE
Video addon

### ISSUE THREAD

**Issue by CkauNui** [CkauNui/ckau-book#26]
I add this later
Current COLORFUL video pack no have:

- [x] laser310
- [x] raze
- [x] eduke32
- [x] fury
- [x] lowresnx
- [x] openjazz
- [x] cgenius
- [x] hcl
- [x] hurrican
- [x] arduboy
- [x] neogeo64

**Comment by Lendersmark** [comment]
All these videos have been added in my last commit to the Colorful Video addon.
These others are still missing:

- [ ] gzdoom
- [ ] hbmame
- [ ] j2me
- [ ] neogeo64
- [ ] neogeomvs
