### ISSUE TITLE
I have a question about how the game software is lined up

### ISSUE THREAD

**Issue by yamanobe96** [CkauNui/ckau-book#27]
Thanks for the great theme!
Very cool with the graphical UI!

I have one question: regarding "automatic" in the default section of gamelist, I would like to set only the right side of the game software sequence to the DETAILED sequence, which setting can I use to do this?

Automatic
https://i.imgur.com/qJYqvit.png
DETAILED
https://i.imgur.com/JGBwJGB.png
I want it to look like this
https://i.imgur.com/zPMV4Rz.png

**Comment by Lendersmark** [comment]
Hi @yamanobe96, the closest result you can get is using the "Detailed Dark" view.
Background will be dark; however, elements will be positioned exactly as in the "Detailed" view (with desctiption under the video, and not vice versa).

**Comment by yamanobe96** [comment]
Thank you.
Thanks to your advice I have found a great subject.
This is my ideal game list!

https://i.imgur.com/qITz9IR.png
