### ISSUE TITLE
System support for megadrive-msu

### ISSUE THREAD

**Issue by virtual-man007** [CkauNui/ckau-book#28]
Please and thank you!

**Comment by g-spawnPL** [comment]
it's already here! i don't know what emulation system you use but you can find megadrive msu under the name msu-md.xml (png has the same name)

**Comment by g-spawnPL** [comment]
> Please and thank you!

it's already here! i don't know what emulation system you use but you can find megadrive msu under the name msu-md.xml (png has the same name)

**Comment by Lendersmark** [comment]
Bug found!
Msu-md support is here, but the png image in` /_inc/anim` is called `megadrive-msu.png` instead of the system name which is msu-md.
Until @CkauNui does the fix in the repo, you can manually rename it to `msu-md.png` and it will work 😉 
If you have downloaded 4K image pack, it needs to be renamed there also.
Thank you @virtual-man007 for reporting!

**Comment by virtual-man007** [comment]
> > Please and thank you!
> 
> it's already here! i don't know what emulation system you use but you can find megadrive msu under the name msu-md.xml (png has the same name)

appreciate it, retrobat uses megadrive-msu for rom path it seems.

**Comment by Lendersmark** [comment]
Bug found!
Megadrive MSU system is named differently between Batocera and Retrobat.
In batocera is named msu-md, while in Retrobat is named megadrive-msu (just checked both https://github.com/batocera-linux/batocera.linux/blob/master/package/batocera/emulationstation/batocera-es-system/es_systems.yml and https://github.com/kaylh/RetroBat/blob/master/system/templates/emulationstation/es_systems_retrobat.cfg)

ckau-book theme has support for both Batocera and Retrobat different system names, but this time we forgot to put megadrive-msu.xml into /_inc/layouts folder.

So, while waiting for @CkauNui to update the repo, the workaround to gain Retrobat compatibility the solution is to manually rename (or, better, duplicate as we usually do in these cases)

`/_inc/layouts/msu-md.xml` into `/_inc/layouts/megadrive-msu.xml`

 Thank you @virtual-man007 for reporting 😉

**Comment by virtual-man007** [comment]
I'm good I managed to adopt appreciate it! m 
![image](https://user-images.githubusercontent.com/33401499/197548708-f84a24fd-843a-4a5c-b14d-f69e40359d17.png)
o
