### ISSUE TITLE
Thank you very much for your work!

### ISSUE THREAD

**Issue by vince59000** [CkauNui/ckau-book#29]
Hi CkauNui, already thank you very much for your work, your theme is just perfect. It's a pleasure to create such a pretty cross-platform system :)

I allow myself to contact you because I would very much like to be able to create some arcade or other systems myself, taking care to make the skins. Could you possibly share your mockups of tv, terminals etc in PSD I imagine? It would be great for me.

Thanking you in advance if you take the time to read me ;)

vincent

**Comment by g-spawnPL** [comment]
> Hi CkauNui, already thank you very much for your work, your theme is just perfect. It's a pleasure to create such a pretty cross-platform system :)
> 
> I allow myself to contact you because I would very much like to be able to create some arcade or other systems myself, taking care to make the skins. Could you possibly share your mockups of tv, terminals etc in PSD I imagine? It would be great for me.
> 
> Thanking you in advance if you take the time to read me ;)
> 
> vincent

Hi,
Most of them you can find here: [https://forums.launchbox-app.com/files/file/2485-colorful-resources/](url)
