### ISSUE TITLE
Retrobat v5 compatibility

### ISSUE THREAD

**Issue by Lendersmark** [CkauNui/ckau-book#32]
- [x] amiga4000 missing
- [x] gba2players missing
- [x] neogeo64 missing (only logo is present)
- [x] msu-md (called megadrive-msu in Retrobat): default video not showing up

**Comment by adesito** [comment]
I have problem in retrobat 5 as the background keeps black and I need to recharge all gamelist after retrobat has booted. I don't knoe if is a theme problem or retrobar problem... I think should be a retrobat problem, but I don't know if you have similar problem or not.

**Comment by Lendersmark** [comment]
Hi @adesito I'm experimenting that too. It happens frequently when scrolling at high speed between systems. Seems like Retrobat doesn't load the next image until it has finished the current one, and giving the scroll command before it has finished loading causes the black screen. Definitely seems a Retrobat v5 bug to me (never happened with v4).
Anyway I close this task since it is not related to it.

**Comment by adesito** [comment]
I got a workaround in retrobat v5. If you put the vRAM to 256MB or below I get the background loading like v4. I raised to 512MB in v4, but I don't know why in v5 you have to put 256MB in VRAM to load the background images corretly.
