### ISSUE TITLE
Remove info panel

### ISSUE THREAD

**Issue by Mikey2000c** [CkauNui/ckau-book#46]
Hey all is there a way to remove the info panel that pops up when on a system for a few seconds. I absolutely love this theme however I just don’t like the info screen ;) any ideas how to remove this or possibly make it a theme configuarion option ? 

Many thanks and great work!!

**Comment by CkauNui** [comment]
please attach a screenshot to understand what you mean

**Comment by Mikey2000c** [comment]
Referring to this panel ![C2747483-2D3C-4D78-953D-497560502E8D](https://user-images.githubusercontent.com/122280572/211314048-60e38cea-118a-41ab-b85e-07138ee2fbff.jpeg)

**Comment by Mikey2000c** [comment]
Legend! Thank you so much !
