### ISSUE TITLE
pl Translation

### ISSUE THREAD

**Issue by g-spawnPL** [CkauNui/ckau-book#47]
https://github.com/CkauNui/ckau-book/blob/7e57b2c8162a59398e4c4ace0867834ef93b1639/_inc/layouts/cdogs.xml#L68

C-Dogs, sequel Cyberdogs, to gra wideo typu shoot'em up, w której gracze współpracują podczas misji, a także przeciwko sobie w trybie "dogfight" deathmatch.
C-Dogs wprowadził zmiany i ulepszenia w mechanice oryginalnej gry Cyberdogs. Rozgrywka dla jednego gracza/kooperacyjna jest podzielona na kampanie, z których każda składa się z wielu misji. Zazwyczaj każdy poziom wymaga od gracza (lub graczy) zabijania wrogów (przy jednoczesnym unikaniu krzywdy cywilów i kolegów z drużyny) przy użyciu różnych wybranych wcześniej broni; zbierania kluczy, aby odblokować specjalne pomieszczenia; i zbierania wymaganych przedmiotów, aby wypełnić cele misji.

Rozgrywka "walki psów" to typowy deathmatch: gracze próbują zabijać się nawzajem za punkty, aby zdobyć zwycięstwo. Tylko dwóch graczy może grać przeciwko sobie, siedząc przy tym samym komputerze i używając klawiatury, joysticków lub gamepadów.

**Comment by Lendersmark** [comment]
Fixed, will be live with the next pull request
