### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by hardknoxni69a** [CkauNui/ckau-book#5]
Your Theme Is Absolutely Amazing. You Should Consider Porting To RetroPie And Attract Mode

**Comment by Lendersmark** [comment]
Hi @hardknoxni69a , I think you can actually use the theme in Retropie since it's an Emulationstation theme.
I'm using it in Retrobat on PC and works flawlessly. The only thing you might have to do is rename some assets (both pngs and xmls) to match the system names you have in your setup.

**Comment by hardknoxni69a** [comment]
Thanks I'll give it a shot honestly batocera runs amazing but I like having the option of desktop use for when I edit stuff yes I can do most of it through terminal but let's face it its nice to drag n drop over cp

**Comment by hardknoxni69a** [comment]
Dam I got excited and tried using on retropie and bummer doesn't work. Retropie uses a different emulation station so not sure what's needed to make it load the extra menu options.

**Comment by Lendersmark** [comment]
@hardknoxni69a you're right. Retrobat on Windows is based on Batocera, so this theme is compatible with Retrobat; but not with Retropie on Pi4.

**Comment by adesito** [comment]
Running in retrobat/emulationstation too. Awesome theme!!! I miss CP-1 CP-2 and CP-3 layouts, but I replicated arcade one to put them in my arcade station :)

**Comment by Lendersmark** [comment]
Hi @adesito, Capcom cps1/cps2/cps3 are now fully supported: check out the new theme version
