### ISSUE TITLE
Support for Nokia N-Gage handheld system for (Retrobat)

### ISSUE THREAD

**Issue by virtual-man007** [CkauNui/ckau-book#52]
Support for Nokia Ngage handheld - got it going front-end friendly. /roms/ngage (if you need assets I have them).

**Comment by virtual-man007** [comment]
Any status on this request, was hoping to showcase with yoru theme. https://youtu.be/0KuTevqslJE

**Comment by CkauNui** [comment]
![ngage](https://user-images.githubusercontent.com/32091297/216799143-6a5ea42c-30cb-4e1d-bcdb-13e133cb720a.png)
ngage has been included in the theme for a long time

**Comment by virtual-man007** [comment]
i don't see the assets please point me to it
