### ISSUE TITLE
Issue: 2 Theme Options Loading

### ISSUE THREAD

**Issue by hardknoxni69a** [CkauNui/ckau-book#8]
Hello and thanks for your work. I noticed today that when choosing cinematic for system view it is also loading the videos that go inside the systems of console from colorful pack as well essentially doubling the resources used. Also the text is still loading behind the videos sometimes hanging out the sides. I am referring to the text that tells you where to load the videos if they are not present. The videos are present so that text should not load? Just a few errors I have noticed so far messing around with the system. I also downloaded the 14 videos that were missing from colorful pack that had videos in the cinematic pack that way the colorful packs are complete. Would you like me to upload somewhere for you that way you can add to your zips and include in your links

**Comment by CkauNui** [comment]
upload in google drive or send me in discord or gmail.
We cant disable text, we use zIndex for hide text.

**Comment by hardknoxni69a** [comment]
Unfortunately it is not hiding the text for some reason if it is supposed to be hidden as I can see it hanging out the side of the videos. And also when when it loads the cinematic videos full screen it is still loading the videos from the colorful pack behind it so each menu option loads 2 videos or 4 videos in the case of arcade/fbneo.

**Comment by CkauNui** [comment]
I upload fix
Check and post result here pls

**Comment by hardknoxni69a** [comment]
Looking good bud. I no longer see the text or the other video loading behind the front video.g

**Comment by hardknoxni69a** [comment]
]
