### ISSUE TITLE
PC Engine shows up as TurboGrafx 16 in system list and game list when Region is set to US

### ISSUE THREAD

**Issue by multigamesystem** [CkauNui/ckau-book#82]
This seems like a bug because I would like to have each system separated as there are Japan specific games for the system.  Maybe include a region option for mixed?  Or something along those lines.  I typically like to have two sets of roms for each region in my frontend but the way you have it now the front end is restricted to only one region at a time.

**Comment by Lendersmark** [comment]
Hi,
Retrobat and Batocera support different versions of the same console at the same time, and ckau-book theme does also, if you have set the default region ("EU") in settings.

For example you can differentiate Super Nintendo and Super Famicom by putting roms in "snes" or "sfc" folder.
Or PC Engine / TuboGrafx 16 (respectively "pcengine" and "tg16" roms folder).

But when you set "US" or "JP" region, all systems will appear as they were named in these regions.

For example:
If region="US", PC Engine will always appear as "Turbografx 16" (even if you have roms in "pcengine" folder)
If region="JP", Super Nintendo will always appear as "Super Famicom" (even if you have roms in "snes" folder), and Sega Master System will appear as "Sega Mark III"

Hope this is enough clear, if you need further info just let us know.

**Comment by multigamesystem** [comment]
Thanks Mark but I wondered if there was a way to get rid of this region locking switch.  So I can have both as separate systems at the sametime without having the logo change when the region is switched.  Or at least give me a region free option?  I don't see what advantage this function has.  Why would someone want the wrong region logo or artwork for another regions rom set?  There should be a way to disable this functionality?

**Comment by Lendersmark** [comment]
@multigamesystem EU = region free.
Just select EU as region and you can keep systems separated: megadrive/genesis, snes/sfc, nes/famicom, etc. by putting roms in the proper directory.
