### ISSUE TITLE
Aspect ratio incorrect for CPS1, CPS2 and CPS3 videos

### ISSUE THREAD

**Issue by multigamesystem** [CkauNui/ckau-book#83]
Incorrect aspect ratio for CPS1, CPS2 and CPS3 videos.   Seems to be set to 16:9

**Comment by Lendersmark** [comment]
Are you using your own (scraped) videos in roms folder or did you install ckau-book Colorful video addon?

It may depend on the single video you're displaying.
If you install the Colorful Video addon (available at https://github.com/CkauNui/ckau-book-addons-Colorful-Video), default videos will always show for each system, and videos for CPS1, CPS2, CPS3 should fit perfectly. Check this screenshot:

![Screenshot 2023-05-18 194315](https://github.com/CkauNui/ckau-book/assets/78660866/8d558c2f-1cee-4e71-8e14-8cdc05ff9ab5)

**Comment by multigamesystem** [comment]
Videos here on the systems screen are fine its in the game list that the scraped video looks stretched wide.  I double checked the resolution and original aspect of the videos.  Its not an error with them.  Its something within the theme config.  All other system themes seem ok just CPS1,2 and 3 are wrong.   I could go into the xmls and compare between a known working theme and the CPS themes.  I might try that when I get a chance.

**Comment by Lendersmark** [comment]
@multigamesystem which view are you using for the game list?

You can customize it in theme options. Globally it can be set through
_User Interface settings -> Theme Configuration -> Gamelist view style_
the default is named "Wallpapersheroes".

You can change it also the gamelist view for a single system, when you're displaying a system
popup menu -> View Options -> Gamelist View Style
