### ISSUE TITLE
More images from screenscraper

### ISSUE THREAD

**Issue by yamanobe96** [CkauNui/ckau-book#85]
Hi, thanks for making a great theme! Very helpful!

Although emulationstation collects image data from screenscraper,
There are various image data in screenscraper
ckau-book uses package images, screenshot title screens and video files, but
screenscraper also has fan art and wheel
Do you plan to use them?

**Comment by CkauNui** [comment]
Hello, I don't quite understand. If u see my youtube - https://www.youtube.com/@Ckau/videos
u can see when wheel and fan-art use.

**Comment by yamanobe96** [comment]
![Коллекция Nintendo 64DD - 22 05 23 - YouTube - Google Chrome 2023_06_24 23_22_43](https://github.com/CkauNui/ckau-book/assets/46581513/34231eb9-b1c8-422f-ab4e-c801dd3a7e69)

Thank you!
I watched the youtube video! I learned a lot!
I have a question, please let me know!
I see in the gamelist.xml
2) <thumbnail> boxart folder
3) <image> art folder
4) <marquee> wheel folder
5) <video> video folder
I found that (5) <video> video folder,
What is the name of the illustration in (1) in the background?

**Comment by CkauNui** [comment]
fanart

**Comment by yamanobe96** [comment]
Thanks, I will edit gamelist.xml in fanart.
Please tell me one last thing.
What is the name of the display style for this video?
https://www.youtube.com/watch?v=Cpz0BSs5OuY
https://www.youtube.com/watch?v=7vsNqT4D3eI

I thought it was wallpapersheroes.
I assigned the wheel image to marquee and the fanart image to fanart.
I guess not.
![全画面プロジェクター (プレビュー) 2023_06_25 8_10_46](https://github.com/CkauNui/ckau-book/assets/46581513/2bf6f6b7-0c27-46b1-ad33-3163cd8aab81)

**Comment by CkauNui** [comment]
wallpapersheroes
<image> - screenshot
<video> - video
<thumbnail> - boxart
<marquee> - wheel
<fanart> - fanart (i use 1920x620)
