### ISSUE TITLE
Noob question

### ISSUE THREAD

**Issue by cyberbol** [CkauNui/ckau-book#87]
Hi everyone.

Sorry for my newbi question,I just start with retro, as I am as well retro. 1981 lol. 
My qyestion is... how to instrall this theme and how download it ?

I downloaded 2TB retro batocera image, Works fine, I even added some more roms, i starting learn. now i want add some themes but I dont know how.
Also how to add repository github ?
How to open terminal in batocera ?

**Comment by g-spawnPL** [comment]
> Hi everyone.
> 
> Sorry for my newbi question,I just start with retro, as I am as well retro. 1981 lol. My qyestion is... how to instrall this theme and how download it ?
> 
> I downloaded 2TB retro batocera image, Works fine, I even added some more roms, i starting learn. now i want add some themes but I dont know how. Also how to add repository github ? How to open terminal in batocera ?

Hi,
check this: https://wiki.batocera.org/themes
