### ISSUE TITLE
Please add Sega Nomad  :.)

### ISSUE THREAD

**Issue by Sleyk2010** [CkauNui/ckau-book#88]
Please add Sega Nomad to Chau-Book Theme. I uploaded all the logos and artwork I could find online. Thanks!

https://en.wikipedia.org/wiki/Genesis_Nomad
https://sega.fandom.com/wiki/Nomad

[Sega Genesis Nomad.zip](https://github.com/CkauNui/ckau-book/files/12063358/Sega.Genesis.Nomad.zip)

**Comment by CkauNui** [comment]
add. Thanks @g-spawnPL and @Lendersmark

**Comment by Sleyk2010** [comment]
Amazing! Thanks! You rock brothers!
