### ISSUE TITLE
Issue/Suggestion: Allow Downsampling

### ISSUE THREAD

**Issue by hardknoxni69a** [CkauNui/ckau-book#9]
Currently The Odroid Go Advance Uses A Screen Of 480x320 So When Using Your 360P Video Themes The Edges Are Cut Off Rather Then Being Downsized. I Am Still Trying To Learn About How Themes And All This Stuff Works But I Am Hoping A Simple Line Of Code Will Fix This So The Edges Aren't Cut Off. Thanks Alot!

**Comment by CkauNui** [comment]
I no have Odroid Go or others for test, need try tinyscreen options in \_inc\systemviews\tinyscreen.xml

**Comment by hardknoxni69a** [comment]
What am I supposed to do with that? Is there a way to make it automatically downsample? Or maybe a different menu option? I'm happy to test whatever I have both the OGA and the OGS

**Comment by CkauNui** [comment]
I upload fix
Check and post result here pls

**Comment by hardknoxni69a** [comment]
The downsample did not work unfortunately so the edges are still cut off on the OGA

**Comment by CkauNui** [comment]
update and check again

**Comment by hardknoxni69a** [comment]
Mission Complete! Great work bud.
